default:
  regions: [us-east-1]
accounts:
  whalerock: []
  wonderwall: []
  momme: []
  bermanbraun: []
  tested: []
  whiskeymedia: []
  analytics: []
  sugarfish: []
  tyler: []
  howard: []
  tyler-stage: []
  howard-stage: []
  kendall-stage: []
  kylie-stage: []
  kim-stage: []
  khloe-stage: []
  kourtney-stage: []
  zendaya-stage: []
  zendaya: []
  kim: []
  purpleclover: []
  kylie: []
  khloe: []
  kendall: []
  kourtney: []
 
